ALTER TABLE "Material"
ADD COLUMN IF NOT EXISTS "price" DECIMAL(10,2);

ALTER TABLE "MaintenanceTaskAssignment"
ADD COLUMN IF NOT EXISTS "startTime" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "endTime" TIMESTAMP(3);
